# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils


DESCRIPTION="Control AppleScriptable applications from Python."
HOMEPAGE="http://appscript.sourceforge.net"
SRC_URI="http://pypi.python.org/packages/source/a/appscript/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~x86-macos"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

